name: Autograding Tests
on: [push, repository_dispatch, workflow_dispatch]
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Onion Packet
      id: onion-packet
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Onion Packet
        setup-command: "./submissions/run.sh $(pwd) $(pwd)/test/input.json"
        command: "./test/onion_check.sh | tail -n 1"
        input: ''
        expected-output: PASS
        comparison-method: exact
        timeout: 10
        max-score: 1
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ONION-PACKET_RESULTS: "${{steps.onion-packet.outputs.result}}"
      with:
        runners: onion-packet
